In [1]:
import sqlite3
import random
import pandas as pd
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

# Create in-memory SQLite connection
conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

In [2]:
## Sample data:
# Parameters
start_date = datetime(2024, 1, 1)
end_date = datetime(2024, 12, 31)
num_rows = 1000

# Generate random sales data
sales_data_large = []
for order_id in range(1, num_rows + 1):
    # Random date between start_date and end_date
    random_days = random.randint(0, (end_date - start_date).days)
    order_date = start_date + timedelta(days=random_days)
    
    # Random sales amount between 50 and 500
    amount = round(random.uniform(50, 500), 2)
    
    sales_data_large.append((order_id, order_date.strftime('%Y-%m-%d'), amount))

# Convert to DataFrame for preview
df_large = pd.DataFrame(sales_data_large, columns=['order_id', 'order_date', 'amount'])
df_large.head()

   order_id  order_date  amount
0         1  2024-11-15  304.88
1         2  2024-06-20  167.86
2         3  2024-02-23  415.79
3         4  2024-03-01  479.87
4         5  2024-06-14  140.26

In [3]:
# Load DataFrame into SQLite table
df_large.to_sql("sales", conn, index=False, if_exists="replace")

1000

#### 1. Calculate Month over Month sales

In [4]:
pd.read_sql_query("""
WITH monthly_sales AS (
    SELECT
    DATE(strftime('%Y-%m-01', order_date)) AS month_start,
    SUM(amount) AS total_sales
    FROM sales
    GROUP BY strftime('%Y-%m', order_date)
    )
    SELECT
    month_start,
    total_sales,
    prev_month_sales,
    total_sales - prev_month_sales AS mom_change,
    concat(coalesce(ROUND((total_sales - prev_month_sales) * 100.0 / prev_month_sales, 2), 0), '%') AS mom_change_pct
    FROM (
        SELECT
        month_start,
        total_sales,
        LAG(total_sales) OVER (ORDER BY month_start) AS prev_month_sales
        FROM monthly_sales
        ) t
    ORDER BY month_start;
""", conn)

   month_start  total_sales  prev_month_sales  mom_change mom_change_pct
0   2024-01-01     19369.29               NaN         NaN             0%
1   2024-02-01     21935.04          19369.29     2565.75         13.25%
2   2024-03-01     19883.94          21935.04    -2051.10         -9.35%
3   2024-04-01     20204.71          19883.94      320.77          1.61%
4   2024-05-01     23386.45          20204.71     3181.74         15.75%
5   2024-06-01     27077.65          23386.45     3691.20         15.78%
6   2024-07-01     23647.89          27077.65    -3429.76        -12.67%
7   2024-08-01     23876.79          23647.89      228.90          0.97%
8   2024-09-01     21198.95          23876.79    -2677.84        -11.22%
9   2024-10-01     22427.40          21198.95     1228.45          5.79%
10  2024-11-01     24538.33          22427.40     2110.93          9.41%
11  2024-12-01     25522.36          24538.33      984.03          4.01%